name: 'compas-actions.docversions'
description: 'Update doc versions list for COMPAS repos'

inputs:
  current_patch:
    description: 'the current patch version number that is being deployed'
    required: true
  only_keep_latest_patch:
    description: 'whether to only keep latest patch or each minor versions'
    required: true
    default: 'true'
  doc_versions_path:
    description: 'the path of doc version list file'
    required: true
    default: 'doc_versions.txt'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo latest > ${{ inputs.doc_versions_path }}
        CURRENT_PATCH=${{ inputs.current_patch }}
        CURRENT_MINOR=${CURRENT_PATCH%.*}
        echo current patch: $CURRENT_PATCH current minor: $CURRENT_MINOR
        for folder in $(ls -rd */ | tr -d '/')
        do
            if [[ $folder =~ ^[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$ ]]; then
                PATCH=$folder
                MINOR=${folder%.*}
                if [[ $PATCH != $CURRENT_PATCH && $MINOR = $CURRENT_MINOR && ${{ inputs.only_keep_latest_patch }} = "true" ]]; then
                    echo $PATCH will be deleted
                    rm -Rf $PATCH
                else
                    echo $PATCH  >> ${{ inputs.doc_versions_path }}
                fi
            fi
        done
        echo updated doc versions:
        cat ${{ inputs.doc_versions_path }}