name: 'compas-actions.docversions'
description: 'Update doc versions list for COMPAS repos'

inputs:
  doc_url:
    description: 'the url of the doc site'
    required: true
  only_keep_latest_patch:
    description: 'whether to only keep latest patch or each minor versions'
    required: true
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'
