name: 'compas-actions.docversions'
description: 'Update doc versions list for COMPAS repos'

inputs:
  current_version:
    description: 'the current doc version number that is being deployed'
    required: true
  only_keep_latest_patch:
    description: 'whether to only keep latest patch or each minor versions'
    required: true
    default: 'true'

runs:
  using: 'node20'
  main: 'dist/index.js'
